### Start a new round
# @name start
POST http://localhost:3000/start
Content-Type: application/json

{
  "meetingId": "meeting-123"
}

###

@roundId = {{start.response.body.roundId}}

### Submit a user's input
POST http://localhost:3000/submit
Content-Type: application/json

{
  "meetingId": "meeting-123",
  "roundId": "{{roundId}}",
  "userId": "user-1",
  "input": "My first input"
}

###

### Submit another user's input
POST http://localhost:3000/submit
Content-Type: application/json

{
  "meetingId": "meeting-123",
  "roundId": "{{roundId}}",
  "userId": "user-2",
  "input": "Another input"
}

###

### Aggregate results
POST http://localhost:3000/aggregate
Content-Type: application/json

{
  "meetingId": "meeting-123",
  "roundId": "{{roundId}}"
}
