@meetingId = SomeTeamsChannelGuid
@roundKey = SomeJiraKey

### Start a new round
# @name start
POST http://localhost:3000/start
Content-Type: application/json

{
  "meetingId": "{{meetingId}}",
  "roundKey": "{{roundKey}}"
}

###

@token = {{start.response.body.token}}

### Submit a user's input
POST http://localhost:3000/submit
Content-Type: application/json

{
  "meetingId": "{{meetingId}}",
  "roundKey": "{{roundKey}}",
  "token": "{{token}}",
  "user": {
    "name": "User One",
    "id": "user-1"
  },
  "score": 5
}

###

### Submit another user's input
POST http://localhost:3000/submit
Content-Type: application/json

{
  "meetingId": "{{meetingId}}",
  "roundKey": "{{roundKey}}",
  "token": "{{token}}",
  "user": {
    "name": "User Two",
    "id": "user-2"
  },
  "score": 3
}

###

### Submit another user's input
POST http://localhost:3000/submit
Content-Type: application/json

{
  "meetingId": "{{meetingId}}",
  "roundKey": "{{roundKey}}",
  "token": "{{token}}",
  "user": {
    "name": "User Three",
    "id": "user-3"
  },
  "score": "skip"
}

###

### Aggregate results
POST http://localhost:3000/aggregate
Content-Type: application/json

{
  "meetingId": "{{meetingId}}",
  "roundKey": "{{roundKey}}",
  "token": "{{token}}"
}
