name: Publish `teams-vote-api`

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Only publish when the example changes
      - src/teams-vote-api/**
      - .github/workflows/teams-vote-api.yml

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  # Make the group unique, but, distinguish between automatic and manual dispatch
  group: render-api-${{ github.ref }}${{ github.event_name == 'workflow_dispatch' && '[dispatch]' || '' }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5 
        with:
          lfs: true
      # Supposedly this speeds up the build
      # https://github.com/actions/setup-node/issues/819#issuecomment-1659698335
      - uses: actions/cache@v4
        with:
          path: '~/.pnpm'
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          check-latest: true
      - name: Install dependencies
        run: pnpm install
        working-directory: '.'
      - name: Build dependencies
        run: pnpm deploy:build
        working-directory: '.'
      - name: Build app
        env: 
          VITE_UI_APP_URL: ${{ vars.TEAMS_UI_URL }}
          TEAMS_PLUGIN_TENANT_ID: ${{ secrets.TEAMS_PLUGIN_TENANT_ID }}
          TEAMS_CHATBOT_CLIENT_ID: ${{ secrets.TEAMS_CHATBOT_CLIENT_ID }}
          TEAMS_CHATBOT_CLIENT_SECRET: ${{ secrets.TEAMS_CHATBOT_CLIENT_SECRET }}
        run: pnpm build
        working-directory: './src/teams-vote-api'
        # TODO run tests
  deploy:
    needs: build
    environment:
      name: render-api
      url: https://teamsvote.onrender.com
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"